"""empty message

Revision ID: 26fb1fd727c2
Revises: 
Create Date: 2021-03-03 12:08:41.808400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fb1fd727c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=64), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('nota_imdb', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filme_ano'), 'filme', ['ano'], unique=False)
    op.create_index(op.f('ix_filme_nota_imdb'), 'filme', ['nota_imdb'], unique=False)
    op.create_index(op.f('ix_filme_titulo'), 'filme', ['titulo'], unique=False)
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('filme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_estrelas'), 'avaliacao', ['estrelas'], unique=False)
    op.create_index(op.f('ix_avaliacao_timestamp'), 'avaliacao', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacao_timestamp'), table_name='avaliacao')
    op.drop_index(op.f('ix_avaliacao_estrelas'), table_name='avaliacao')
    op.drop_table('avaliacao')
    op.drop_index(op.f('ix_filme_titulo'), table_name='filme')
    op.drop_index(op.f('ix_filme_nota_imdb'), table_name='filme')
    op.drop_index(op.f('ix_filme_ano'), table_name='filme')
    op.drop_table('filme')
    # ### end Alembic commands ###
