"""empty message

Revision ID: 28d638db5e5a
Revises: 
Create Date: 2021-03-14 18:59:44.151058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d638db5e5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('senha_hash', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('nacionalidade', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_index(op.f('ix_usuario_nacionalidade'), 'usuario', ['nacionalidade'], unique=False)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=False)
    op.create_index(op.f('ix_usuario_senha_hash'), 'usuario', ['senha_hash'], unique=False)
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_nome', sa.String(length=64), nullable=True),
    sa.Column('produto_dsc', sa.String(length=512), nullable=True),
    sa.Column('qtd_estoque', sa.Integer(), nullable=True),
    sa.Column('qtd_vendidos', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('avaliacao', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_avaliacao'), 'estoque', ['avaliacao'], unique=False)
    op.create_index(op.f('ix_estoque_preco'), 'estoque', ['preco'], unique=False)
    op.create_index(op.f('ix_estoque_produto_dsc'), 'estoque', ['produto_dsc'], unique=False)
    op.create_index(op.f('ix_estoque_produto_nome'), 'estoque', ['produto_nome'], unique=False)
    op.create_index(op.f('ix_estoque_qtd_estoque'), 'estoque', ['qtd_estoque'], unique=False)
    op.create_index(op.f('ix_estoque_qtd_vendidos'), 'estoque', ['qtd_vendidos'], unique=False)
    op.create_index(op.f('ix_estoque_timestamp'), 'estoque', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estoque_timestamp'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_qtd_vendidos'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_qtd_estoque'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_produto_nome'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_produto_dsc'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_preco'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_avaliacao'), table_name='estoque')
    op.drop_table('estoque')
    op.drop_index(op.f('ix_usuario_senha_hash'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nacionalidade'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
