"""empty message

Revision ID: a29b84c56015
Revises: 28d638db5e5a
Create Date: 2021-03-15 00:15:38.223409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29b84c56015'
down_revision = '28d638db5e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuario_senha_hash', table_name='usuario')
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.drop_index('ix_usuario_nome', table_name='usuario')
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.create_index('ix_usuario_nome', 'usuario', ['nome'], unique=False)
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=False)
    op.create_index('ix_usuario_senha_hash', 'usuario', ['senha_hash'], unique=False)
    # ### end Alembic commands ###
